version: '0.2'
ignorePaths:
  - .gitignore
  - devcontainer.json
  - .vscode/settings.json
dictionaryDefinitions: []
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - node
  - typescript
  - html
  - css
words:
  - bodawala
  - devcontainer
  - devcontainers
  - pgadmin
  - pranav
  - typebox
ignoreWords:
  - dpage
  - noninteractive
import: []
language: en
enabled: true
